In [ ]:
#Librerías de manejo de datos
import pandas as pd
import numpy as np

In [ ]:
# Ruta relativa desde el notebook
file_path = '../datasets/raw/car_manufacturing_data.csv'

In [4]:
df = pd.read_csv(file_path)

In [5]:
df_original = df.copy()

# 1. Preparación de los datos. Preprocesa los datos con Pandas y Numpy para el análisis de Machine Learning

In [6]:
df.head()

    Car_ID Production_Date Engine_Type Production_Line          Cost  Defects
0  CAR0001      2021-01-01    Electric          Line 3           NaN        0
1  CAR0002      2021-01-02          V6          Line 3  21946.767413        0
2  CAR0003      2021-01-03    Electric          Line 3  27617.462418        3
3  CAR0004      2021-01-04    Electric          Line 1  27406.281885        3
4  CAR0005      2021-01-05          V6          Line 3  40889.128185        4

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Car_ID           110 non-null    object
 1   Production_Date  110 non-null    object
 2   Engine_Type      110 non-null    object
 3   Production_Line  110 non-null    object
 4   Cost             99 non-null     float64
 5   Defects          110 non-null    int64
dtypes: float64(1), int64(1), object(4)
memory usage: 5.3+ KB

In [ ]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Cost,99.0,38783.393017,11551.686634,20542.260908,28839.272526,39030.540341,45837.895548,74750.585817
Defects,110.0,1.918182,1.421537,0.000000,1.000000,2.000000,3.000000,4.000000

In [ ]:
df.isnull().sum()

Car_ID              0
Production_Date     0
Engine_Type         0
Production_Line     0
Cost               11
Defects             0
dtype: int64

## Tratando de detectar valores atípicos (outliers) o incorrectos

In [ ]:
# Seleccionar todas las columnas de tipo 'object' (normalmente cadenas de texto)
text_columns = df.select_dtypes(include='object').columns

# Mostrar las columnas de texto
print(text_columns)

Index(['Car_ID', 'Production_Date', 'Engine_Type', 'Production_Line'], dtype='object')

In [ ]:
for col in text_columns:
    print(f"\nColumna: {col}")
    print(df[col].value_counts())

Columna: Car_ID
Car_ID
CAR0015    2
CAR0045    2
CAR0056    2
CAR0098    2
CAR0038    2
          ..
CAR0033    1
CAR0032    1
CAR0031    1
CAR0030    1
CAR0100    1
Name: count, Length: 100, dtype: int64

Columna: Production_Date
Production_Date
2021-01-15    2
2021-02-14    2
2021-02-25    2
2021-04-08    2
2021-02-07    2
             ..
2021-02-02    1
2021-02-01    1
2021-01-31    1
2021-01-30    1
2021-04-10    1
Name: count, Length: 100, dtype: int64

Columna: Engine_Type
Engine_Type
V6          37
V8          37
Electric    36
Name: count, dtype: int64

Columna: Production_Line
Production_Line
Line 3    48
Line 1    35
Line 2    27
Name: count, dtype: int64

## Número de valores únicos

In [ ]:
df['Car_ID'].nunique()

100

In [ ]:
df['Production_Date'].nunique()

100

In [ ]:
df['Car_ID'].duplicated().sum()

10

In [ ]:
df['Production_Date'].duplicated().sum()

10

In [ ]:
# Filas duplicadas en Car_ID
df[df['Car_ID'].duplicated(keep=False)].sort_values('Car_ID')

,Car_ID,Production_Date,Engine_Type,Production_Line,Cost,Defects
5,CAR0006,2021-01-06,V6,Line 3,62052.176547,4
101,CAR0006,2021-01-06,V6,Line 3,41368.117698,4
13,CAR0014,2021-01-14,Electric,Line 3,39030.540341,2
108,CAR0014,2021-01-14,Electric,Line 3,39030.540341,2
109,CAR0015,2021-01-15,V8,Line 1,40421.163547,3
14,CAR0015,2021-01-15,V8,Line 1,40421.163547,3
37,CAR0038,2021-02-07,Electric,Line 3,22885.296533,1
103,CAR0038,2021-02-07,Electric,Line 3,22885.296533,1
105,CAR0044,2021-02-13,V6,Line 2,63084.725366,3
43,CAR0044,2021-02-13,V6,Line 2,42056.483577,3
44,CAR0045,2021-02-14,V6,Line 1,26272.148622,1
106,CAR0045,2021-02-14,V6,Line 1,26272.148622,1
55,CAR0056,2021-02-25,Electric,Line 3,69718.635444,2
102,CAR0056,2021-02-25,Electric,Line 3,46479.090296,2
70,CAR0071,2021-03-12,Electric,Line 2,NaN,3
104,CAR0071,2021-03-12,Electric,Line 2,NaN,3
81,CAR0082,2021-03-23,V6,Line 3,42325.115692,1
107,CAR0082,2021-03-23,V6,Line 3,42325.115692,1
100,CAR0098,2021-04-08,Electric,Line 3,40358.337071,0
97,CAR0098,2021-04-08,Electric,Line 3,26905.558047,0

In [ ]:
df.head(20)

     Car_ID Production_Date Engine_Type Production_Line          Cost  Defects
0   CAR0001      2021-01-01    Electric          Line 3           NaN        0
1   CAR0002      2021-01-02          V6          Line 3  21946.767413        0
2   CAR0003      2021-01-03    Electric          Line 3  27617.462418        3
3   CAR0004      2021-01-04    Electric          Line 1  27406.281885        3
4   CAR0005      2021-01-05          V6          Line 3  40889.128185        4
5   CAR0006      2021-01-06          V6          Line 3  62052.176547        4
6   CAR0007      2021-01-07    Electric          Line 1  24442.607899        2
7   CAR0008      2021-01-08          V8          Line 3  49932.214551        3
8   CAR0009      2021-01-09    Electric          Line 1  28003.430428        0
9   CAR0010      2021-01-10    Electric          Line 2  49298.448675        4
10  CAR0011      2021-01-11    Electric          Line 3           NaN        4
11  CAR0012      2021-01-12    Electric          Line 2  20991.521987        0
12  CAR0013      2021-01-13          V6          Line 1  30352.137441        4
13  CAR0014      2021-01-14    Electric          Line 3  39030.540341        2
14  CAR0015      2021-01-15          V8          Line 1  40421.163547        3
15  CAR0016      2021-01-16          V6          Line 2  53892.056249        0
16  CAR0017      2021-01-17          V8          Line 1  33433.494937        3
17  CAR0018      2021-01-18          V8          Line 3  36586.792672        4
18  CAR0019      2021-01-19          V8          Line 3  37780.901716        4
19  CAR0020      2021-01-20          V8          Line 2  22425.599790        0

In [ ]:
# Eliminar duplicados, conservando el primer  registro según el índice
df = df.drop_duplicates(subset=['Car_ID', 'Production_Date'], keep='first')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Car_ID           100 non-null    object
 1   Production_Date  100 non-null    object
 2   Engine_Type      100 non-null    object
 3   Production_Line  100 non-null    object
 4   Cost             90 non-null     float64
 5   Defects          100 non-null    int64
dtypes: float64(1), int64(1), object(4)
memory usage: 5.5+ KB

In [ ]:
# Eliminar filas con Cost nulo
df = df.dropna(subset=['Cost'])

# Verificar
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 1 to 99
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Car_ID           90 non-null     object
 1   Production_Date  90 non-null     object
 2   Engine_Type      90 non-null     object
 3   Production_Line  90 non-null     object
 4   Cost             90 non-null     float64
 5   Defects          90 non-null     int64
dtypes: float64(1), int64(1), object(4)
memory usage: 4.9+ KB

In [2]:
print(df)

NameError: name 'df' is not defined

In [8]:
!where python

C:\Users\j_c_a\AppData\Local\Programs\Python\Python39\python.exe
C:\Users\j_c_a\.pyenv\pyenv-win\shims\python
C:\Users\j_c_a\AppData\Local\Microsoft\WindowsApps\python.exe

In [ ]:
# NOTE: It's not pointing out to the venv created
import sys
print(sys.executable)

c:\Users\j_c_a\.pyenv\pyenv-win\versions\3.9.13\python.exe